export const authConstants = {
    LOGIN_REQUEST: 'LOGIN_REQUEST',
    LOGIN_FAILURE: 'LOGIN_FAILURE',
    ADMIN_LOGIN_SUCCESS: 'ADMIN_LOGIN_SUCCESS',
    STORE_LOGIN_SUCCESS: 'STORE_LOGIN_SUCCESS',
    LOGOUT_REQUEST: 'LOGOUT_REQUEST',
    LOGOUT_SUCCESS: 'LOGOUT_SUCCESS',
    LOGOUT_FAILURE: 'LOGOUT_FAILURE'



}


export const userContants = {
    USER_REGISTER_REQUEST: 'USER_REGISTER_REQUEST',
    USER_REGISTER_SUCCESS: ' USER_REGISTER_SUCCESS',
    USER_REGISTER_FAILURE: ' USER_REGISTER_FAILURE'

}

export const categoryContants = {
    GET_ALL_CATEGORIES_REQUEST: 'GET_ALL_CATEGORIES_REQUEST',
    GET_ALL_CATEGORIES_SUCCESS: 'GET_ALL_CATEGORIES_SUCCESS',
    GET_ALL_CATEGORIES_FAILURE: 'GET_ALL_CATEGORIES_FAILURE',
    ADD_NEW_CATEGORY_REQUEST: 'ADD_NEW_CATEGORY_REQUEST',
    ADD_NEW_CATEGORY_SUCCESS: 'ADD_NEW_CATEGORY_SUCCESS',
    ADD_NEW_CATEGORY_FAILURE: 'ADD_NEW_CATEGORY_FAILURE',
    UPDATE_CATEGORY_REQUEST: 'UPDATE_CATEGORY_REQUEST',
    UPDATE_CATEGORY_SUCCESS: 'UPDATE_CATEGORY_SUCCESS',
    UPDATE_CATEGORY_FAILURE: 'UPDATE_CATEGORY_FAILURE',
    DELETE_CATEGORY_REQUEST: 'DELETE_CATEGORY_REQUEST',
    DELETE_CATEGORY_SUCCESS: 'DELETE_CATEGORY_SUCCESS',
    DELETE_CATEGORY_FAILURE: 'DELETE_CATEGORY_FAILURE'


}
export const locationContants = {
    GET_ALL_LOCATION_REQUEST: 'GET_ALL_LOCATION_REQUEST',
    GET_ALL_LOCATION_SUCCESS: 'GET_ALL_LOCATION_SUCCESS',
    GET_ALL_LOCATION_FAILURE: 'GET_ALL_LOCATION_FAILURE',
    ADD_NEW_LOCATION_REQUEST: 'ADD_NEW_LOCATION_REQUEST',
    ADD_NEW_LOCATION_SUCCESS: 'ADD_NEW_LOCATION_SUCCESS',
    ADD_NEW_LOCATION_FAILURE: 'ADD_NEW_LOCATION_FAILURE',
 


}




export const productContants = {
    GET_ALL_PRODUCTS_REQUEST: 'GET_ALL_PRODUCTS_REQUEST',
    GET_ALL_PRODUCTS_SUCCESS: 'GET_ALL_PRODUCTS_SUCCESS',
    GET_ALL_PRODUCTS_FAILURE: 'GET_ALL_PRODUCTS_FAILURE',
    ADD_NEW_PRODUCT_REQUEST: 'ADD_NEW_PRODUCT_REQUEST',
    ADD_NEW_PRODUCT_SUCCESS: 'ADD_NEW_PRODUCT_SUCCESS',
    ADD_NEW_PRODUCT_FAILURE: 'ADD_NEW_PRODUCT_FAILURE',
    DELETE_PRODUCT_BY_ID_REQUEST: "DELETE_PRODUCT_BY_ID_REQUEST",
    DELETE_PRODUCT_BY_ID_SUCCESS: "DELETE_PRODUCT_BY_ID_SUCCESS",
    DELETE_PRODUCT_BY_ID_FAILURE: "DELETE_PRODUCT_BY_ID_FAILURE",
    EDIT_PRODUCT_BY_ID_REQUEST: "EDIT_PRODUCT_BY_ID_REQUEST",
    EDIT_PRODUCT_BY_ID_SUCCESS: "EDIT_PRODUCT_BY_ID_SUCCESS",
    EDIT_PRODUCT_BY_ID_FAILURE: "EDIT_PRODUCT_BY_ID_FAILURE",

}



export const initialDataContants = {

    GET_ALL_INITIAL_DATA_REQUEST: 'GET_ALL_INITIAL_DATA_REQUEST',
    GET_ALL_INITIAL_DATA_FAILURE: 'GET_ALL_INITIAL_DATA_FAILURE',
    GET_ALL_INITIAL_DATA_SUCCESS: 'GET_ALL_INITIAL_DATA_SUCCESS',
}

export const storeContants = {
    
GET_ALL_STORE_REQUEST: 'GET_ALL_STORE_REQUEST',
GET_ALL_STORE_SUCCESS: 'GET_ALL_STORE_SUCCESS',
GET_ALL_STORE_FAILURE: 'GET_ALL_STORE_FAILURE',
GET_ALL_NEW_STORE_SUCCESS: 'GET_ALL_NEW_STORE_SUCCESS',
ADD_NEW_STORE_REQUEST: 'ADD_NEW_STORE_REQUEST',
ADD_NEW_STORE_SUCCESS: 'ADD_NEW_STORE_SUCCESS',
ADD_NEW_STORE_FAILURE: 'ADD_NEW_STORE_FAILURE',

GET_STORE_DETAILS_BY_ID_REQUEST: 'GET_STORE_DETAILS_BY_ID_REQUEST',
GET_STORE_DETAILS_BY_ID_SUCCESS: 'GET_STORE_DETAILS_BY_ID_SUCCESS',
GET_STORE_DETAILS_BY_ID_FAILURE: 'GET_STORE_DETAILS_BY_ID_FAILURE'


 
};

export const pageConstants ={
    CREATE_PAGE_REQUEST : 'CREATE_PAGE_REQUEST',
    CREATE_PAGE_SUCCESS : 'CREATE_PAGE_SUCCESS',
    CREATE_PAGE_FAILURE : 'CREATE_PAGE_FAILURE '
};

export const orderConstants = {
    GET_CUSTOMER_ORDER_REQUEST: "GET_CUSTOMER_ORDER_REQUEST",
    GET_CUSTOMER_ORDER_SUCCESS: "GET_CUSTOMER_ORDER_SUCCESS",
    GET_CUSTOMER_ORDER_FAILURE: "GET_CUSTOMER_ORDER_FAILURE",
  
    UPDATE_CUSTOMER_ORDER_REQUEST: "UPDATE_CUSTOMER_ORDER_REQUEST",
    UPDATE_CUSTOMER_ORDER_SUCCESS: "UPDATE_CUSTOMER_ORDER_SUCCESS",
    UPDATE_CUSTOMER_ORDER_FAILURE: "UPDATE_CUSTOMER_ORDER_FAILURE",

    GET_ORDER_DETAILS_BY_ID_REQUEST: 'GET_ORDER_DETAILS_BY_ID_REQUEST',
    GET_ORDER_DETAILS_BY_ID_SUCCESS: 'GET_ORDER_DETAILS_BY_ID_SUCCESS',
    GET_ORDER_DETAILS_BY_ID_FAILURE: 'GET_ORDER_DETAILS_BY_ID_FAILURE'
  };



  export const storeDataContants = {

    GET_ALL_STORE_DATA_REQUEST: 'GET_ALL_STORE_DATA_REQUEST',
    GET_ALL_STORE_DATA_FAILURE: 'GET_ALL_STORE_DATA_FAILURE',
    GET_ALL_STORE_DATA_SUCCESS: 'GET_ALL_STORE_DATA_SUCCESS',
    EDIT_STORE_DATA_REQUEST: 'EDIT_STORE_DATA_REQUEST',
    EDIT_STORE_DATA_SUCCESS:'EDIT_STORE_DATA_SUCCESS',
    EDIT_STORE_DATA_FAILURE:'EDIT_STORE_DATA_FAILURE'
}